version: '3.9'

x-dpractics: &dpractics
  build:
    context: .
    dockerfile: ./package/dpractics/Dockerfile
  volumes:
    - ./src:/src

services:
  
  rabbit:
    image: rabbitmq:management
    
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  queue:
    <<: *dpractics
    container_name: queue
    command: poetry run python -m at_queue -H rabbit -dh 0.0.0.0 -dp 7777
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ps -p $(cat /var/run/at_queue/pidfile.pid) || exit 1
      interval: 1s
      timeout: 3s
      retries: 30

  at_controller:
    <<: *dpractics
    container_name: at_controller
    command: poetry run python -m at_controller -H rabbit
    depends_on:
      queue:
        condition: service_healthy
    environment:
      AT_SIMULATION_FRONT_PORT: ${AT_SIMULATION_FRONT_PORT}
      AT_KRL_EDITOR_FRONT_PORT: ${AT_KRL_EDITOR_FRONT_PORT}
      AT_JOINT_DEBUGGER_PORT: ${AT_JOINT_DEBUGGER_PORT}
    healthcheck:
      test: ps -p $(cat /var/run/at_controller/pidfile.pid) || exit 1
      interval: 1s
      timeout: 3s
      retries: 30
  
  at_renderer:
    <<: *dpractics
    container_name: at_renderer
    command: poetry run python -m at_renderer -H rabbit -sh 0.0.0.0 -sp 8888
    depends_on:
      queue:
        condition: service_healthy
    healthcheck:
      test: ps -p $(cat /var/run/at_renderer/pidfile.pid) || exit 1
      interval: 1s
      timeout: 3s
      retries: 30
      
  configurator:
    <<: *dpractics
    container_name: configurator
    command: poetry run python -m at_configurator -H rabbit -c /src/config.yaml
    depends_on:
      at_controller:
        condition: service_healthy
      at_renderer:
        condition: service_healthy

  nginx:
    build: ./package/nginx
    ports:
      - 8888:8888
      - 7777:7777
    depends_on:
      at_renderer:
        condition: service_healthy
    expose:
      - 8888
      - 7777

  
  
  